version: 0.2.{build}
configuration: Release
skip_tags: true
environment:
    git_token:
        secure: zOalLNVugkdAgWERo3MRA2k/t1RAgaVvnCjR6lFsh2/i3Zwy45h7lT3T9pSTuigo
assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'
nuget:
  project_feed: true
before_build:
  - appveyor DownloadFile https://raw.githubusercontent.com/appveyor/ci/master/scripts/nuget-restore.cmd
  - nuget-restore
build:
  publish_nuget: true
  verbosity: minimal 
test_script:
  - nunit-console Ve.Messaging.Tests\bin\Release\Ve.Messaging.Tests.dll
artifacts:
- path: Ve.Messaging.*.nupkg
  name: NuGet Package
cache:
- packages -> **\packages.config
deploy:
  provider: NuGet
  api_key:
    secure: 9VQU1tM1eJOhWwZvwKm00ndEGr+GPyeYm49nWZPWDDmNvKYe4z+mmeGtHe+R9GDh 
  skip_symbols: false
  artifact: /.*\.nupkg/
on_success:
    - git config --global credential.helper store
    - ps: Add-Content "$env:USERPROFILE\.git-credentials" "https://$($env:git_token):x-oauth-basic@github.com`n"
    - git tag -a release/%APPVEYOR_BUILD_VERSION% -m "Added tag"
    - git push origin release/%APPVEYOR_BUILD_VERSION%

